# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def validar_numeros(cpf):
    if len(cpf) == 11 and cpf.isnumeric():
      return True
    else:
      return False

def validar_digito_1(cpf):
    lista_cpf = []
    peso = 10
    for n in range(0, (len(cpf) - 2)):
        digito = int(cpf[n]) * peso
        lista_cpf.append(digito)
        peso -= 1
    soma = sum(lista_cpf)
    resultado = int((((soma * 10) % 11) % 10))
    if resultado == int(cpf[9]):
      return True
    else:
      return False

def validar_digito_2(cpf):
    lista_cpf = []
    peso = 11
    for n in range(0, (len(cpf) - 1)):
        digito = int(cpf[n]) * peso
        lista_cpf.append(digito)
        peso -= 1
    soma = sum(lista_cpf)
    resultado = int((((soma * 10) % 11) % 10))
    if resultado == int(cpf[10]):
        return True
    else:
        return False

def validar_cpf(numeros, digito1, digito2):
    if numeros == True and digito1 == True and digito2 == True:
      print('CPF Valido!')
    else:
      print('CPF Invalido!')

cpf = str(input('Digite o CPF: ')).strip()
numeros = validar_numeros(cpf)
digito1 = validar_digito_1(cpf)
digito2 = validar_digito_2(cpf)

validar_cpf(numeros, digito1, digito2)