# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Soma recursiva
def soma_r(n):
  if n == 1:
    return 1
  return n + soma_r(n-1)

soma_r(15)

#Fibonacci
def fbc(n):
  if n == 1 or n == 2 :
    return n
  return fbc(n-1) + fbc(n-2)

fbc(5)

#Fibonacci
[f(n) for n in range (1,8)]

#pi
def pi(n):
  den = list(range(1, 2*n,2)) #list denominador
  return 4*sum ([1/((2*x+1)*(-1)**x) for x in range(n)])

pi(1)

