# -*- coding: utf-8 -*-
"""Cópia_de_Olá,_este_é_o_Colaboratory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rahgay2mZZZfN1mpyg_snp5C0LhQrOu7
"""

#Ex1

list = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]

cont = 0
cont_list = len(list)

while (cont != cont_list):
  print(f"{cont}: "+ f"{list[cont]}")
  cont = cont + 1

#Ex2


lista = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]

list2 = lista
list2.reverse()
print(list2)

#Ex 3

Idade = [15, 20, 35, 18, 50]
idademax = max(Idade)
idademin = min(Idade)

print(f"Maior Idade:{idademax}")
print(f"Menor Idade:{idademin}")

#Ex 4

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

impar = []
par = []

for numero in numeros:
    if numero % 2 == 0:
        par.append(numero)
    else:
        impar.append(numero)

print(f"Lista Impar: {impar}")
print(f"Lista Par: {par}")

#Ex 5

lista1 = [10, 1, 2, 3, 4, 5]
lista2 = [6, 7, 8, 9, 0]

lista1.insert(1,lista2[-1])
lista2.pop(-1)
lista2.append(lista1[0])
lista1.pop(0)

print(lista1 + lista2)


#outro metodo

lista3 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(lista3[-1],lista3[1:-1],lista3[0])

#Ex 6

#Um loop cria uma os 3 numeros da linha e o outro para criar as outras linhas.

#Ex 7

nomeUsuario = input("Olá, digite seu nome: ")

saldoDisponivel = float(input(f"{nomeUsuario}, qual seu saldo disponivel? Digite:"))

produtos = {
  'camiseta': (25.00, 10),
  'calça': (45.00, 5),
  'sapato': (60.00, 3),
  'boné': (15.00, 8)}

cont = 1

for nome, preco in produtos.items():
  if preco[0] <= saldoDisponivel:

    print(f"{cont} - {nome} - R${int(preco[0])}")
    cont = cont + 1

#Ex 8

nomeAtleta = input("Olá, digite o nome do atleta: ")
print(" ")

cont = 0
notas = []

while cont != 7:
  nota = float(input("Insira a nota da atleta: "))
  notas.append(nota)
  cont = cont + 1

print(" ")
print("----------------------------------")
print(" ")

notas.sort()
#notas.pop(0)
#notas.pop(-1)
notas = notas[1:-1]
media = sum(notas) / 5

cont = 0
while cont != 5:
  print(f"Nota: {notas[cont]}")
  cont = cont + 1

print(" ")
print(f"A media do {nomeAtleta} é: {media}")